### ISSUE TITLE
Not working on ruby 1.9.3 and rspec 2

### ISSUE THREAD

**Issue by adilsoncarvalho** [lsegal/yard-spec-plugin#4]
This idea of putting the specs within the docs are great.

I've installed the plugin, but it doesn't find my specs to add on the documentation as shown in your live demo.

I've also cloned your repo and tried your example, and it worked.

I was thinking that maybe the plugin is not beign loaded, so I've added the following config on my ~/.yard/config

```

---
load_plugins: true
autoload_plugins:
  - yard-rspec
```

Then to check it out I went to /usr/local/rvm/gems/ruby-1.9.3-p0/gems/yard-rspec-0.1/lib/ and put a puts just to see if the plugin is called, and surprise, I is called.

Is there something I am missing to set up?

**Comment by lsegal** [comment]
``` sh
$ git clone git://github.com/lsegal/yard-spec-plugin
$ cd yard-spec-plugin
$ yard -e ./lib/yard-rspec.rb example
$ open doc/index.html
```

Works for me.

Also:

``` sh
$ gem install yard-rspec
$ cd yard-spec-plugin (after checkout)
$ yard --plugin rspec example
$ open doc/index.html
```

**Comment by adilsoncarvalho** [comment]
Hi,

Just got what was wrong, the directory structure. My source was on lib/dir/_.rb and my tests on spec/__spec.rb.

After I put all my tests on spec/dir/*_spec.rb all worked well.
